# WEB SCRAPPING 
- Objetivo: Criar uma base de dados contendo o MCC correspondente ao CNAE digitado

**Importando bibliotecas necessárias**

In [1]:
import pyautogui
import time
import pyperclip
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import urllib

**Carregando a base de dados que será usada para input de informações**

In [2]:
df = pd.read_excel("C:\\Users\\Tuta\\Desktop\\cnae_mcc.xlsx")
display(df)

,codigo,descricao,mcc,mcc_descricao
0,111301,Cultivo de arroz,NaN,NaN
1,111302,Cultivo de milho,NaN,NaN
2,111303,Cultivo de trigo,NaN,NaN
3,111399,Cultivo de outros cereais não especificados an...,NaN,NaN
4,112101,Cultivo de algodão herbáceo,NaN,NaN
...,...,...,...,...
1354,9609208,Higiene e embelezamento de animais domésticos,NaN,NaN
1355,9609299,Outras atividades de serviços pessoais não esp...,NaN,NaN
1356,9700500,Serviços domésticos,NaN,NaN
1357,9900800,Organismos internacionais e outras instituiçõe...,NaN,NaN
1358,8888888,Atividade Econônica não informada,NaN,NaN

**Robo coletador de dados**

**ACQIO**

In [6]:
# Definição do site para consulta
navegador = webdriver.Chrome()
navegador.get("https://acqio.com.br/mcc/")

# Cordenada para input
loc = navegador.find_element_by_xpath('/html/body/section/div/div[2]/div[1]/form/div/input')

# Cordenada para reiniciar
fecha = navegador.find_element_by_xpath('/html/body/div[1]/div/div/div[2]/button')

# Tempo de espera
time.sleep(5)

# Processo de input e coleta
for i, codigo in enumerate(df['codigo']):
    try:
        loc.clear()
        time.sleep(1)
        loc.send_keys(codigo)
        time.sleep(1)
        loc.send_keys(Keys.ENTER)
        time.sleep(5)
        fecha.click()
        time.sleep(1)
        #loc.send_keys(Keys.ENTER)
        mcc_num = navegador.find_element_by_xpath('/html/body/section/div/div[2]/div[2]/ul/li[3]').text
        mcc_des = navegador.find_element_by_xpath('/html/body/section/div/div[2]/div[2]/ul/li[4]').text
        df.loc[i,"mcc"] = mcc_num
        df.loc[i,"mcc_descricao"] = mcc_des
    except:
        pass

In [7]:
#Cria novas colunas para nova coleta em outra fonte
df["mcc_2"] = np.nan
df["mcc_2_descricao"] = np.nan
df.to_csv('C:\\Users\\Tuta\\Desktop\\cnae_mcc.csv', sep='\t', encoding='UTF-8')
display(df)

,codigo,descricao,mcc,mcc_descricao,mcc_2,mcc_2_descricao
0,111301,Cultivo de arroz,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa,NaN,NaN
1,111302,Cultivo de milho,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa,NaN,NaN
2,111303,Cultivo de trigo,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa,NaN,NaN
3,111399,Cultivo de outros cereais não especificados an...,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa,NaN,NaN
4,112101,Cultivo de algodão herbáceo,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa,NaN,NaN
...,...,...,...,...,...,...
1354,9609208,Higiene e embelezamento de animais domésticos,Nº do MCC: 7298,DESCRIÇÃO DO MCC: Personal Trainer,NaN,NaN
1355,9609299,Outras atividades de serviços pessoais não esp...,Nº do MCC: 7298,DESCRIÇÃO DO MCC: Personal Trainer,NaN,NaN
1356,9700500,Serviços domésticos,Nº do MCC: 7349,DESCRIÇÃO DO MCC: Serviços de Manutenção e Lim...,NaN,NaN
1357,9900800,Organismos internacionais e outras instituiçõe...,Nº do MCC: 5051,DESCRIÇÃO DO MCC: Serviços de Siderurgia,NaN,NaN
1358,8888888,Atividade Econônica não informada,NaN,NaN,NaN,NaN

**SIPAG**

In [9]:
navegador = webdriver.Chrome()
navegador.get("https://acqio.com.br/mcc/")
loc = navegador.find_element_by_xpath('/html/body/section/div/div[2]/div[1]/form/div/input')
fecha = navegador.find_element_by_xpath('/html/body/div[1]/div/div/div[2]/button')
time.sleep(5)
    
for i, codigo in enumerate(df['codigo']):
    try:
        loc.clear()
        time.sleep(1)
        loc.send_keys(codigo)
        time.sleep(1)
        loc.send_keys(Keys.ENTER)
        time.sleep(9)
        fecha.click()
        time.sleep(1)
        #loc.send_keys(Keys.ENTER)
        mcc_num = navegador.find_element_by_xpath('/html/body/section/div/div[2]/div[2]/ul/li[3]').text
        mcc_des = navegador.find_element_by_xpath('/html/body/section/div/div[2]/div[2]/ul/li[4]').text
        df.loc[i,"mcc_2"] = mcc_num
        df.loc[i,"mcc_2_descricao"] = mcc_des
    except:
        passnavegador = webdriver.Chrome()
navegador.get("https://www.sipag.com.br/")
loc = navegador.find_element_by_xpath('/html/body/div[4]/div/section[2]/div/div/div/main/div/div[6]/div/div[1]/div[2]/div/input')
enter = navegador.find_element_by_xpath('/html/body/div[4]/div/section[2]/div/div/div/main/div/div[6]/div/div[1]/div[2]/div/div/button')
time.sleep(5)
    
for i, codigo in enumerate(df['codigo']):
    try:
        loc.clear()
        time.sleep(1)
        loc.send_keys(codigo)
        time.sleep(1)
        enter.click()
        time.sleep(3)
        #loc.send_keys(Keys.ENTER)
        mcc_num = navegador.find_element_by_xpath('/html/body/div[4]/div/section[2]/div/div/div/main/div/div[6]/div/div[1]/div[3]/table/tbody/tr[2]/td[3]').text
        cnae_num = navegador.find_element_by_xpath('/html/body/div[4]/div/section[2]/div/div/div/main/div/div[6]/div/div[1]/div[3]/table/tbody/tr[2]/td[2]').text
        df.loc[i,"mcc_2"] = mcc_num
        df.loc[i,"mcc_2_descricao"] = cnae_num
    except:
        pass

In [10]:
df.to_csv('C:\\Users\\Tuta\\Desktop\\cnae_mcc.csv', sep='\t', encoding='UTF-8')
display(df)

,codigo,descricao,mcc,mcc_descricao,mcc_2,mcc_2_descricao
0,111301,Cultivo de arroz,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa
1,111302,Cultivo de milho,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa
2,111303,Cultivo de trigo,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa
3,111399,Cultivo de outros cereais não especificados an...,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa
4,112101,Cultivo de algodão herbáceo,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa,Nº do MCC: 763,DESCRIÇÃO DO MCC: Agricultura cooperativa
...,...,...,...,...,...,...
1354,9609208,Higiene e embelezamento de animais domésticos,Nº do MCC: 7298,DESCRIÇÃO DO MCC: Personal Trainer,Nº do MCC: 5995,DESCRIÇÃO DO MCC: Petshops
1355,9609299,Outras atividades de serviços pessoais não esp...,Nº do MCC: 7298,DESCRIÇÃO DO MCC: Personal Trainer,Nº do MCC: 7299,DESCRIÇÃO DO MCC: Atelier
1356,9700500,Serviços domésticos,Nº do MCC: 7349,DESCRIÇÃO DO MCC: Serviços de Manutenção e Lim...,Nº do MCC: 7349,DESCRIÇÃO DO MCC: Serviços de Manutenção e Lim...
1357,9900800,Organismos internacionais e outras instituiçõe...,Nº do MCC: 5051,DESCRIÇÃO DO MCC: Serviços de Siderurgia,Nº do MCC: 8999,DESCRIÇÃO DO MCC: Serviços Profissionais Não R...
1358,8888888,Atividade Econônica não informada,NaN,NaN,NaN,NaN

In [14]:
df.isnull().sum()

codigo              0
descricao           0
mcc                78
mcc_descricao      78
mcc_2              74
mcc_2_descricao    74
mcc_3              75
mcc_3_descricao    75
dtype: int64